import { test, expect } from "@playwright/test";
import { launchApp, closeApp } from "../helpers/app";
import { S } from "../helpers/selectors";
import {
  clickRequestTab,
  typeUrl,
  selectMethod,
  sendRequest,
  clickResponseTab,
  TEST_URLS,
} from "../helpers/data";
import type { Page } from "@playwright/test";

// ═══════════════════════════════════════════════════════════════════════
// UF-03: Request Building
// Covers: method selection, URL & params, headers, body types (raw,
//         form-data, x-www-form-urlencoded, graphql, binary, none),
//         payloads, auth (none/bearer/basic + badge), captures UI,
//         format button, {{var}} in auth fields, {{var}} in body types,
//         undefined var fallback, DELETE with body
// ═══════════════════════════════════════════════════════════════════════

let page: Page;

test.beforeAll(async () => {
  ({ page } = await launchApp());
});

test.afterAll(async () => {
  await closeApp();
});

// ── URL & Method ──────────────────────────────────────────────────────

test.describe("URL & Method", () => {
  test("method dropdown cycles through all HTTP methods", async () => {
    const methods = ["GET", "POST", "PUT", "PATCH", "DELETE"];
    for (const method of methods) {
      await selectMethod(page, method);
      await expect(page.locator(S.methodSelect)).toHaveValue(method);
    }
    await selectMethod(page, "GET");
  });

  test("typing URL updates the input field", async () => {
    await typeUrl(page, "https://httpbin.org/get");
    const urlInput = page.locator(`${S.urlBar} .autosuggest-wrapper input`);
    await expect(urlInput).toHaveValue("https://httpbin.org/get");
  });

  test("URL with query string auto-populates params table", async () => {
    await typeUrl(page, "https://httpbin.org/get?foo=bar&baz=qux");
    await clickRequestTab(page, "Params");

    const rows = page.locator(S.kvRow);
    const count = await rows.count();
    expect(count).toBeGreaterThanOrEqual(2);
  });

  test("adding param row appends to URL query string", async () => {
    await typeUrl(page, "https://httpbin.org/get");
    await clickRequestTab(page, "Params");

    const firstRow = page.locator(S.kvRow).first();
    const keyInput = firstRow.locator(".autosuggest-wrapper input").first();
    const valueInput = firstRow.locator(".autosuggest-wrapper input").nth(1);

    await keyInput.fill("testKey");
    await valueInput.fill("testValue");

    const urlInput = page.locator(`${S.urlBar} .autosuggest-wrapper input`);
    await expect(urlInput).toHaveValue(/testKey=testValue/);
  });

  test("disabling param row removes it from URL", async () => {
    await clickRequestTab(page, "Params");

    const firstRow = page.locator(S.kvRow).first();
    const checkbox = firstRow.locator('input[type="checkbox"]');
    await checkbox.uncheck();

    const urlInput = page.locator(`${S.urlBar} .autosuggest-wrapper input`);
    await expect(urlInput).not.toHaveValue(/testKey=testValue/);

    await checkbox.check();
  });

  test("removing param removes from URL", async () => {
    await clickRequestTab(page, "Params");

    const removeBtn = page.locator(S.kvRow).first().locator(S.kvRemoveBtn);
    await removeBtn.click();

    const newUrl = await page
      .locator(`${S.urlBar} .autosuggest-wrapper input`)
      .inputValue();
    expect(newUrl).not.toContain("testKey");
  });
});

// ── Request Headers ───────────────────────────────────────────────────

test.describe("Request Headers", () => {
  test("Headers panel shows KeyValueEditor", async () => {
    await clickRequestTab(page, "Headers");
    await expect(
      page.locator(`${S.requestSection} ${S.kvEditor}`),
    ).toBeVisible();
  });

  test("add header row via Add button", async () => {
    await clickRequestTab(page, "Headers");
    const initialCount = await page.locator(S.kvRow).count();

    await page.click(S.kvAddBtn);

    const newCount = await page.locator(S.kvRow).count();
    expect(newCount).toBe(initialCount + 1);
  });

  test("remove header removes row", async () => {
    await clickRequestTab(page, "Headers");
    const countBefore = await page.locator(S.kvRow).count();

    const lastRemove = page.locator(S.kvRemoveBtn).last();
    await lastRemove.click();

    const countAfter = await page.locator(S.kvRow).count();
    expect(countAfter).toBe(countBefore - 1);
  });

  test("autogenerated headers section is visible", async () => {
    await clickRequestTab(page, "Headers");
    await expect(page.locator(S.autogeneratedHeaders)).toBeVisible();

    const rows = page.locator(S.autogeneratedHeaderRow);
    const count = await rows.count();
    expect(count).toBeGreaterThanOrEqual(3);
  });

  test("header key input shows autocomplete dropdown with standard headers", async () => {
    await clickRequestTab(page, "Headers");

    const firstRow = page.locator(S.kvRow).first();
    const keyInput = firstRow.locator(".autosuggest-wrapper input").first();
    await keyInput.click();
    await keyInput.fill("Content");

    await expect(page.locator(S.autosuggestDropdown)).toBeVisible();

    const items = page.locator(S.autosuggestItem);
    const count = await items.count();
    expect(count).toBeGreaterThan(0);

    const firstItemText = await items.first().textContent();
    expect(firstItemText).toContain("Content");

    await keyInput.press("Escape");
  });
});

// ── Request Body ──────────────────────────────────────────────────────

test.describe("Request Body", () => {
  test("default body type is none with info message", async () => {
    // Open a fresh tab for body tests
    await page.click(S.tabAdd);
    await clickRequestTab(page, "Body");
    await expect(page.locator(S.bodyNoneInfo)).toBeVisible();
  });

  test('selecting "raw" shows CodeEditor and language dropdown', async () => {
    await clickRequestTab(page, "Body");
    await page.locator(`${S.bodyTypeOption}:has-text("raw")`).click();

    await expect(page.locator(S.rawLanguageSelect)).toBeVisible();
    await expect(page.locator(S.codeEditorWrapper)).toBeVisible();
  });

  test("raw language dropdown switches between options", async () => {
    const languages = ["json", "text", "xml", "html", "javascript"];
    for (const lang of languages) {
      await page.selectOption(S.rawLanguageSelect, lang);
      await expect(page.locator(S.rawLanguageSelect)).toHaveValue(lang);
    }
  });

  test('selecting "form-data" shows key/value table with type column', async () => {
    await page.locator(`${S.bodyTypeOption}:has-text("form-data")`).click();

    await expect(page.locator(S.formDataEditor)).toBeVisible();
    await expect(page.locator(S.formDataTypeSelect).first()).toBeVisible();
  });

  test("form-data add and remove rows work", async () => {
    const initialRows = await page.locator(S.formDataRow).count();
    await page.click(`${S.formDataEditor} ${S.kvAddBtn}`);

    const afterAdd = await page.locator(S.formDataRow).count();
    expect(afterAdd).toBe(initialRows + 1);

    await page.locator(`${S.formDataRow} ${S.kvRemoveBtn}`).last().click();
    const afterRemove = await page.locator(S.formDataRow).count();
    expect(afterRemove).toBe(afterAdd - 1);
  });

  test('selecting "x-www-form-urlencoded" shows key/value without type column', async () => {
    await page
      .locator(`${S.bodyTypeOption}:has-text("x-www-form-urlencoded")`)
      .click();

    await expect(page.locator(S.formDataEditor)).toBeVisible();
    await expect(page.locator(S.formDataTypeSelect)).toHaveCount(0);
  });

  test('selecting "graphql" shows query and variables editors', async () => {
    await page.locator(`${S.bodyTypeOption}:has-text("graphql")`).click();

    await expect(page.locator(S.graphqlEditor)).toBeVisible();

    const sections = page.locator(S.graphqlSection);
    await expect(sections).toHaveCount(2);

    const labels = page.locator(S.graphqlLabel);
    const labelTexts = await labels.allTextContents();
    expect(labelTexts.some((l) => l.includes("Query"))).toBe(true);
    expect(labelTexts.some((l) => l.includes("Variables"))).toBe(true);
  });

  test("graphql variables editor has format button", async () => {
    const formatBtns = page.locator(`${S.graphqlEditor} ${S.formatBtn}`);
    await expect(formatBtns.first()).toBeVisible();
  });

  test('selecting "binary" shows file path input', async () => {
    await page.locator(`${S.bodyTypeOption}:has-text("binary")`).click();

    await expect(page.locator(S.binaryEditor)).toBeVisible();
    await expect(page.locator(S.binaryPathInput)).toBeVisible();
  });

  test('switching back to "none" shows info message', async () => {
    await page.locator(`${S.bodyTypeOption}:has-text("none")`).click();
    await expect(page.locator(S.bodyNoneInfo)).toBeVisible();
  });

  test("payload tabs show default payload", async () => {
    await page.locator(`${S.bodyTypeOption}:has-text("raw")`).click();

    await expect(page.locator(S.payloadTab)).toHaveCount(1);
    const name = page.locator(`${S.payloadTab} ${S.payloadTabName}`).first();
    await expect(name).toHaveText("Default");
  });

  test("add payload creates new tab", async () => {
    await page.click(S.payloadAddBtn);
    await expect(page.locator(S.payloadTab)).toHaveCount(2);
  });

  test("switch between payload tabs preserves body content", async () => {
    const secondPayload = page.locator(S.payloadTab).nth(1);
    await secondPayload.click();

    const firstPayload = page.locator(S.payloadTab).first();
    await firstPayload.click();

    await expect(page.locator(S.payloadTab)).toHaveCount(2);
  });

  test("remove payload tab works when multiple exist", async () => {
    const closeBtn = page.locator(
      `${S.payloadTab}:nth-child(2) ${S.payloadTabClose}`,
    );
    await closeBtn.click();

    await expect(page.locator(S.payloadTab)).toHaveCount(1);
  });
});

// ── Payload Rename (request panel) ────────────────────────────────────

test.describe("Payload Rename (request panel)", () => {
  test("rename payload via payload-rename-input", async () => {
    // Use the tab from previous describe (still has raw body)
    await clickRequestTab(page, "Body");
    // Ensure raw is selected
    await page.locator(`${S.bodyTypeOption}:has-text("raw")`).click();

    await expect(page.locator(S.payloadTab)).toHaveCount(1);

    const renameInput = page.locator(".payload-rename-input");
    await expect(renameInput).toBeVisible();
    await expect(renameInput).toHaveValue("Default");

    await renameInput.fill("My Payload");
    await expect(renameInput).toHaveValue("My Payload");

    const tabName = page.locator(`${S.payloadTab} ${S.payloadTabName}`).first();
    await expect(tabName).toHaveText("My Payload");
  });

  test("add second payload and rename it", async () => {
    await page.click(S.payloadAddBtn);
    await expect(page.locator(S.payloadTab)).toHaveCount(2);

    await page.locator(S.payloadTab).nth(1).click();

    const renameInput = page.locator(".payload-rename-input");
    await renameInput.fill("Variant B");
    await expect(renameInput).toHaveValue("Variant B");

    const tabName = page.locator(`${S.payloadTab} ${S.payloadTabName}`).nth(1);
    await expect(tabName).toHaveText("Variant B");
  });
});

// ── Request Auth ──────────────────────────────────────────────────────

test.describe("Request Auth", () => {
  test('default auth is "No Auth" with info message', async () => {
    await clickRequestTab(page, "Auth");

    await expect(page.locator(S.authTypeSelect)).toHaveValue("none");
    await expect(page.locator(S.authInfo)).toBeVisible();
  });

  test('selecting "Bearer Token" shows token input', async () => {
    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "bearer");

    await expect(page.locator(S.authFields)).toBeVisible();
    const labels = page.locator(S.authLabel);
    const labelTexts = await labels.allTextContents();
    expect(labelTexts.some((l) => l.includes("Token"))).toBe(true);
  });

  test("bearer auth info shows Authorization header preview", async () => {
    const info = page.locator(S.authInfo);
    await expect(info).toBeVisible();
    const text = await info.textContent();
    expect(text).toContain("Authorization");
    expect(text).toContain("Bearer");
  });

  test('selecting "Basic Auth" shows username and password inputs', async () => {
    await page.selectOption(S.authTypeSelect, "basic");

    await expect(page.locator(S.authFields)).toBeVisible();
    const labels = page.locator(S.authLabel);
    const labelTexts = await labels.allTextContents();
    expect(labelTexts.some((l) => l.includes("Username"))).toBe(true);
    expect(labelTexts.some((l) => l.includes("Password"))).toBe(true);
  });

  test("basic auth info shows Base64 preview", async () => {
    const info = page.locator(S.authInfo);
    await expect(info).toBeVisible();
    const text = await info.textContent();
    expect(text).toContain("Basic");
  });
});

// ── Auth Tab Badge ────────────────────────────────────────────────────

test.describe("Auth Tab Badge", () => {
  test("auth badge hidden when type is none", async () => {
    // Open a fresh tab
    await page.click(S.tabAdd);
    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "none");

    await clickRequestTab(page, "Params");
    const authTab = page.locator(`${S.requestTab}:has-text("auth")`);
    const badge = authTab.locator(S.tabBadge);
    await expect(badge).toBeHidden();
  });

  test("auth badge shows ● when bearer auth is set", async () => {
    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "bearer");

    const tokenInput = page.locator(`${S.authFields} input`).first();
    await tokenInput.fill("my-token");

    await clickRequestTab(page, "Params");
    const authTab = page.locator(`${S.requestTab}:has-text("auth")`);
    const badge = authTab.locator(S.tabBadge);
    await expect(badge).toBeVisible();
    await expect(badge).toHaveText("●");
  });

  test("auth badge shows ● when basic auth is set", async () => {
    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "basic");

    await clickRequestTab(page, "Params");
    const authTab = page.locator(`${S.requestTab}:has-text("auth")`);
    const badge = authTab.locator(S.tabBadge);
    await expect(badge).toBeVisible();

    // Reset auth to none
    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "none");
  });
});

// ── Response Captures UI ──────────────────────────────────────────────

test.describe("Response Captures UI", () => {
  test('empty captures shows "No captures yet" message', async () => {
    await clickRequestTab(page, "Captures");
    await expect(page.locator(S.capturesEmpty)).toBeVisible();
  });

  test("warning shows when no environment is selected", async () => {
    await clickRequestTab(page, "Captures");

    const envSelect = page.locator(S.envSelect);
    const currentVal = await envSelect.inputValue();
    if (!currentVal || currentVal === "") {
      await expect(page.locator(S.capturesWarning)).toBeVisible();
    }
  });

  test("add capture creates row with all fields", async () => {
    await clickRequestTab(page, "Captures");
    await page.click(S.captureAddBtn);

    const row = page.locator(S.captureRow);
    await expect(row).toHaveCount(1);

    await expect(row.locator('input[type="checkbox"]')).toBeVisible();
    await expect(row.locator(S.captureVarInput)).toBeVisible();
    await expect(row.locator(S.captureSourceSelect)).toBeVisible();
    await expect(row.locator(S.captureRemoveBtn)).toBeVisible();
  });

  test("source dropdown has Body, Header, Status options", async () => {
    const sourceSelect = page.locator(S.captureSourceSelect).first();
    const options = sourceSelect.locator("option");
    const values = await options.allTextContents();
    expect(values.some((v) => v.includes("Body"))).toBe(true);
    expect(values.some((v) => v.includes("Header"))).toBe(true);
    expect(values.some((v) => v.includes("Status"))).toBe(true);
  });

  test("path input hidden when source is status", async () => {
    const sourceSelect = page.locator(S.captureSourceSelect).first();
    await sourceSelect.selectOption("status");

    await expect(page.locator(S.capturePathInput)).toHaveCount(0);

    await sourceSelect.selectOption("body");
    await expect(page.locator(S.capturePathInput).first()).toBeVisible();
  });

  test("toggle capture enabled/disabled via checkbox", async () => {
    const checkbox = page
      .locator(`${S.captureRow} input[type="checkbox"]`)
      .first();

    await expect(checkbox).toBeChecked();

    await checkbox.uncheck();
    await expect(checkbox).not.toBeChecked();

    await checkbox.check();
    await expect(checkbox).toBeChecked();
  });

  test("remove capture removes row", async () => {
    await expect(page.locator(S.captureRow)).toHaveCount(1);
    await page.locator(S.captureRemoveBtn).first().click();
    await expect(page.locator(S.captureRow)).toHaveCount(0);
  });
});

// ── Format Button ─────────────────────────────────────────────────────

test.describe("Format Button", () => {
  test("format button visible for raw JSON body", async () => {
    await page.click(S.tabAdd);

    await selectMethod(page, "POST");
    await typeUrl(page, TEST_URLS.post);

    await clickRequestTab(page, "Body");
    await page.locator(`${S.bodyTypeOption}:has-text("raw")`).click();
    await page.selectOption(S.rawLanguageSelect, "json");

    const formatBtn = page.locator(S.formatBtn);
    await expect(formatBtn).toBeVisible();
  });

  test("format button formats JSON content", async () => {
    const cmContent = page.locator(`${S.requestSection} .cm-content`).first();
    await cmContent.click();
    await page.keyboard.type('{"a":1,"b":2}');

    await page.waitForTimeout(300);

    await page.click(S.formatBtn);

    await page.waitForFunction(
      () => {
        const cm = document.querySelector(".request-section .cm-content");
        const lines = cm?.querySelectorAll(".cm-line");
        return lines && lines.length > 1;
      },
      { timeout: 5000 },
    );

    const text = await cmContent.textContent();
    expect(text?.length ?? 0).toBeGreaterThan('{"a":1,"b":2}'.length);
  });
});

// ── DELETE With Body ──────────────────────────────────────────────────

test.describe("DELETE With Body", () => {
  test("DELETE request can send a raw JSON body", async () => {
    await page.click(S.tabAdd);
    await selectMethod(page, "DELETE");
    await typeUrl(page, TEST_URLS.delete);

    await clickRequestTab(page, "Body");
    await page.locator(`${S.bodyTypeOption}:has-text("raw")`).click();
    await page.selectOption(S.rawLanguageSelect, "json");

    const cmContent = page.locator(`${S.requestSection} .cm-content`).first();
    await cmContent.click();
    await page.keyboard.type('{"deleteId": 42}');

    await sendRequest(page);

    const statusText = await page.locator(S.responseStatus).textContent();
    expect(statusText).toContain("200");

    await clickResponseTab(page, "Body");
    const bodyContent = page.locator(`${S.responseBody} .cm-content`);
    const text = await bodyContent.textContent();
    expect(text).toContain("deleteId");
  });
});

// ── NEW: {{var}} in Auth Fields ───────────────────────────────────────

test.describe("{{var}} in Auth Fields", () => {
  test("set up environment for auth var tests", async () => {
    // Create env with token variable
    await page.click(S.envManageBtn);
    await expect(page.locator(S.modal)).toBeVisible();

    const addBtn = page.locator(`${S.envList} ${S.sidebarIconBtn}`);
    await addBtn.click();

    const nameInput = page.locator(S.envNameInput);
    await nameInput.fill("AuthVarEnv");

    await page.click(`${S.modal} .kv-add-btn`);
    const lastRow = page.locator(S.envVarRow).last();
    const inputs = lastRow.locator('input[type="text"]');
    await inputs.first().fill("myToken");
    await inputs.nth(1).fill("secret-bearer-token");

    await page.click(`${S.modal} .kv-add-btn`);
    const lastRow2 = page.locator(S.envVarRow).last();
    const inputs2 = lastRow2.locator('input[type="text"]');
    await inputs2.first().fill("myUser");
    await inputs2.nth(1).fill("admin");

    await page.click(`${S.modal} .kv-add-btn`);
    const lastRow3 = page.locator(S.envVarRow).last();
    const inputs3 = lastRow3.locator('input[type="text"]');
    await inputs3.first().fill("myPass");
    await inputs3.nth(1).fill("password123");

    await page.click(S.modalCloseBtn);
    await page.locator(S.envSelect).selectOption({ label: "AuthVarEnv" });
  });

  test("{{var}} in bearer token sends resolved Authorization header", async () => {
    await page.click(S.tabAdd);
    await typeUrl(page, TEST_URLS.headers);
    await selectMethod(page, "GET");

    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "bearer");

    const tokenInput = page.locator(`${S.authFields} input`).first();
    await tokenInput.fill("{{myToken}}");

    await sendRequest(page);

    // httpbin /headers echoes back all headers
    await clickResponseTab(page, "Body");
    const bodyContent = page.locator(`${S.responseBody} .cm-content`);
    const text = await bodyContent.textContent();
    expect(text).toContain("secret-bearer-token");
  });

  test("{{var}} in basic auth username/password encodes correctly", async () => {
    await page.click(S.tabAdd);
    await typeUrl(page, TEST_URLS.headers);
    await selectMethod(page, "GET");

    await clickRequestTab(page, "Auth");
    await page.selectOption(S.authTypeSelect, "basic");

    const inputs = page.locator(`${S.authFields} input`);
    await inputs.first().fill("{{myUser}}");
    await inputs.nth(1).fill("{{myPass}}");

    await sendRequest(page);

    // httpbin /headers echoes back Authorization header as Base64
    await clickResponseTab(page, "Body");
    const bodyContent = page.locator(`${S.responseBody} .cm-content`);
    const text = await bodyContent.textContent();
    // Base64 of "admin:password123" = "YWRtaW46cGFzc3dvcmQxMjM="
    expect(text).toContain("Basic");
    expect(text).toContain("YWRtaW46cGFzc3dvcmQxMjM=");
  });
});

// ── NEW: Undefined Variable Fallback ──────────────────────────────────

test.describe("Undefined Variable Fallback", () => {
  test("undefined {{var}} is sent as literal text", async () => {
    await page.click(S.tabAdd);
    await typeUrl(page, TEST_URLS.headers);
    await selectMethod(page, "GET");

    // Add a header with an undefined variable
    await clickRequestTab(page, "Headers");
    const headerRows = page.locator(S.kvRow);
    const firstRow = headerRows.first();
    await firstRow.locator('input[type="text"]').first().fill("X-Undefined");
    await firstRow.locator('input[type="text"]').nth(1).fill("{{noExistVar}}");

    await sendRequest(page);

    // httpbin /headers echoes back all headers
    await clickResponseTab(page, "Body");
    const bodyContent = page.locator(`${S.responseBody} .cm-content`);
    const text = await bodyContent.textContent();
    // Undefined vars are sent as literal text
    expect(text).toContain("{{noExistVar}}");
  });
});
