import { test, expect } from "@playwright/test";
import { launchApp, closeApp } from "../helpers/app";
import { S } from "../helpers/selectors";
import { clickRequestTab } from "../helpers/data";
import type { Page } from "@playwright/test";

let page: Page;

test.beforeAll(async () => {
  ({ page } = await launchApp());
});

test.afterAll(async () => {
  await closeApp();
});

test.describe("Request Headers", () => {
  test("Headers panel shows KeyValueEditor", async () => {
    await clickRequestTab(page, "Headers");
    await expect(
      page.locator(`${S.requestSection} ${S.kvEditor}`),
    ).toBeVisible();
  });

  test("add header row via Add button", async () => {
    await clickRequestTab(page, "Headers");
    const initialCount = await page.locator(S.kvRow).count();

    await page.click(S.kvAddBtn);

    const newCount = await page.locator(S.kvRow).count();
    expect(newCount).toBe(initialCount + 1);
  });

  test("remove header removes row", async () => {
    await clickRequestTab(page, "Headers");
    const countBefore = await page.locator(S.kvRow).count();

    // Remove the last row
    const lastRemove = page.locator(S.kvRemoveBtn).last();
    await lastRemove.click();

    const countAfter = await page.locator(S.kvRow).count();
    expect(countAfter).toBe(countBefore - 1);
  });

  test("autogenerated headers section is visible", async () => {
    await clickRequestTab(page, "Headers");
    await expect(page.locator(S.autogeneratedHeaders)).toBeVisible();

    // Should show User-Agent, Accept, etc.
    const rows = page.locator(S.autogeneratedHeaderRow);
    const count = await rows.count();
    expect(count).toBeGreaterThanOrEqual(3);
  });

  test("header key input shows autocomplete dropdown with standard headers", async () => {
    await clickRequestTab(page, "Headers");

    // Focus the key input of the first row and type a common header prefix
    const firstRow = page.locator(S.kvRow).first();
    const keyInput = firstRow.locator(".autosuggest-wrapper input").first();
    await keyInput.click();
    await keyInput.fill("Content");

    // Autocomplete dropdown should appear with matching headers
    await expect(page.locator(S.autosuggestDropdown)).toBeVisible();

    const items = page.locator(S.autosuggestItem);
    const count = await items.count();
    expect(count).toBeGreaterThan(0);

    // First item should contain "Content"
    const firstItemText = await items.first().textContent();
    expect(firstItemText).toContain("Content");

    // Close dropdown by pressing Escape
    await keyInput.press("Escape");
  });
});
