import React from "react";
import type { BodyType, RawLanguage } from "../types/electron";

interface AutoGeneratedHeadersProps {
  bodyType: BodyType;
  rawLanguage: RawLanguage;
  headers: { enabled: boolean; key: string; value: string }[];
}

const AutoGeneratedHeaders: React.FC<AutoGeneratedHeadersProps> = ({
  bodyType,
  rawLanguage,
  headers,
}) => (
  <div className="autogenerated-headers">
    <div className="autogenerated-headers-title">
      Auto-generated headers
      <span className="autogenerated-headers-hint">
        (override by adding a header with the same key)
      </span>
    </div>
    <div className="autogenerated-header-row">
      <span className="header-key">User-Agent</span>
      <span className="header-value">ReqResFlow/1.0</span>
    </div>
    <div className="autogenerated-header-row">
      <span className="header-key">Accept</span>
      <span className="header-value">*/*</span>
    </div>
    <div className="autogenerated-header-row">
      <span className="header-key">Accept-Encoding</span>
      <span className="header-value">gzip, deflate, br</span>
    </div>
    <div className="autogenerated-header-row">
      <span className="header-key">Connection</span>
      <span className="header-value">keep-alive</span>
    </div>
    {bodyType !== "none" &&
      bodyType !== "binary" &&
      !headers.some(
        (h) => h.enabled && h.key.toLowerCase() === "content-type",
      ) && (
        <div className="autogenerated-header-row">
          <span className="header-key">Content-Type</span>
          <span className="header-value">
            {bodyType === "raw"
              ? {
                  json: "application/json",
                  text: "text/plain",
                  xml: "application/xml",
                  html: "text/html",
                  javascript: "application/javascript",
                }[rawLanguage] || "text/plain"
              : bodyType === "x-www-form-urlencoded"
                ? "application/x-www-form-urlencoded"
                : bodyType === "form-data"
                  ? "multipart/form-data"
                  : bodyType === "graphql"
                    ? "application/json"
                    : ""}
          </span>
        </div>
      )}
  </div>
);

export default AutoGeneratedHeaders;
