import React from "react";
import AutoGeneratedHeaders from "./AutoGeneratedHeaders";
import AuthEditor from "./AuthEditor";
import BodyEditor from "./BodyEditor";
import CapturesEditor from "./CapturesEditor";
import KeyValueEditor from "./KeyValueEditor";
import { Payload, RequestTab, ResponseCapture } from "../types/electron";
import { getBaseUrl, buildQueryString } from "../utils/url";

type RequestPanel = "params" | "headers" | "body" | "auth" | "captures";

interface RequestPanelSectionProps {
  activeTab: RequestTab;
  requestPanel: RequestPanel;
  onRequestPanelChange: (panel: RequestPanel) => void;
  envVariables: { key: string; value: string }[];
  envName?: string;
  onUpdateTab: (updates: Partial<RequestTab>) => void;
  activePayload: Payload | null;
  body: string;
  onAddPayload: () => void;
  onRemovePayload: (id: string) => void;
  onRenamePayload: (id: string, name: string) => void;
  onUpdatePayloadBody: (value: string) => void;
  activeEnvId: string | null;
  onAddCapture: () => void;
  onUpdateCapture: (id: string, updates: Partial<ResponseCapture>) => void;
  onRemoveCapture: (id: string) => void;
}

const RequestPanelSection: React.FC<RequestPanelSectionProps> = ({
  activeTab,
  requestPanel,
  onRequestPanelChange,
  envVariables,
  envName,
  onUpdateTab,
  activePayload,
  body,
  onAddPayload,
  onRemovePayload,
  onRenamePayload,
  onUpdatePayloadBody,
  activeEnvId,
  onAddCapture,
  onUpdateCapture,
  onRemoveCapture,
}) => (
  <div className="request-section">
    <div className="tabs">
      {(
        ["params", "headers", "body", "auth", "captures"] as RequestPanel[]
      ).map((tab) => (
        <button
          key={tab}
          className={`tab ${requestPanel === tab ? "active" : ""}`}
          onClick={() => onRequestPanelChange(tab)}
        >
          {tab}
          {tab === "auth" && activeTab.auth.type !== "none" && (
            <span className="tab-badge">●</span>
          )}
          {tab === "captures" && activeTab.captures.length > 0 && (
            <span className="tab-badge">
              {activeTab.captures.filter((c) => c.enabled).length}
            </span>
          )}
        </button>
      ))}
    </div>

    {requestPanel === "params" && (
      <KeyValueEditor
        pairs={activeTab.params}
        onChange={(p) => {
          const base = getBaseUrl(activeTab.url);
          const qs = buildQueryString(p);
          const url = qs ? `${base}?${qs}` : base;
          onUpdateTab({ params: p, url });
        }}
        variables={envVariables}
        envName={envName}
      />
    )}
    {requestPanel === "headers" && (
      <>
        <KeyValueEditor
          pairs={activeTab.headers}
          onChange={(h) => onUpdateTab({ headers: h })}
          variables={envVariables}
          envName={envName}
          headerMode
        />
        <AutoGeneratedHeaders
          bodyType={activeTab.bodyType}
          rawLanguage={activeTab.rawLanguage}
          headers={activeTab.headers}
        />
      </>
    )}
    {requestPanel === "body" && (
      <BodyEditor
        tab={activeTab}
        activePayload={activePayload}
        body={body}
        envVariables={envVariables}
        envName={envName}
        onUpdateTab={onUpdateTab}
        onAddPayload={onAddPayload}
        onRemovePayload={onRemovePayload}
        onRenamePayload={onRenamePayload}
        onUpdatePayloadBody={onUpdatePayloadBody}
      />
    )}
    {requestPanel === "auth" && (
      <AuthEditor
        auth={activeTab.auth}
        envVariables={envVariables}
        envName={envName}
        onAuthChange={(auth) => onUpdateTab({ auth })}
      />
    )}
    {requestPanel === "captures" && (
      <CapturesEditor
        captures={activeTab.captures}
        activeEnvId={activeEnvId}
        onAdd={onAddCapture}
        onUpdate={onUpdateCapture}
        onRemove={onRemoveCapture}
      />
    )}
  </div>
);

export type { RequestPanel };
export default RequestPanelSection;
