export const HTTP_HEADER_NAMES = [
  "Accept",
  "Accept-Charset",
  "Accept-Encoding",
  "Accept-Language",
  "Accept-Ranges",
  "Access-Control-Allow-Credentials",
  "Access-Control-Allow-Headers",
  "Access-Control-Allow-Methods",
  "Access-Control-Allow-Origin",
  "Access-Control-Expose-Headers",
  "Access-Control-Max-Age",
  "Access-Control-Request-Headers",
  "Access-Control-Request-Method",
  "Age",
  "Allow",
  "Authorization",
  "Cache-Control",
  "Connection",
  "Content-Disposition",
  "Content-Encoding",
  "Content-Language",
  "Content-Length",
  "Content-Location",
  "Content-Range",
  "Content-Security-Policy",
  "Content-Type",
  "Cookie",
  "Date",
  "DNT",
  "ETag",
  "Expect",
  "Expires",
  "Forwarded",
  "From",
  "Host",
  "If-Match",
  "If-Modified-Since",
  "If-None-Match",
  "If-Range",
  "If-Unmodified-Since",
  "Keep-Alive",
  "Last-Modified",
  "Link",
  "Location",
  "Max-Forwards",
  "Origin",
  "Pragma",
  "Proxy-Authorization",
  "Range",
  "Referer",
  "Retry-After",
  "Sec-Fetch-Dest",
  "Sec-Fetch-Mode",
  "Sec-Fetch-Site",
  "Server",
  "Set-Cookie",
  "Strict-Transport-Security",
  "TE",
  "Trailer",
  "Transfer-Encoding",
  "Upgrade",
  "User-Agent",
  "Vary",
  "Via",
  "Warning",
  "WWW-Authenticate",
  "X-Content-Type-Options",
  "X-Forwarded-For",
  "X-Forwarded-Host",
  "X-Forwarded-Proto",
  "X-Frame-Options",
  "X-Request-ID",
  "X-Requested-With",
  "X-XSS-Protection",
];

export const HEADER_VALUE_SUGGESTIONS: Record<string, string[]> = {
  Accept: [
    "application/json",
    "application/xml",
    "text/html",
    "text/plain",
    "*/*",
    "application/octet-stream",
    "application/x-www-form-urlencoded",
    "multipart/form-data",
    "image/png",
    "image/jpeg",
    "image/webp",
    "application/pdf",
  ],
  "Accept-Charset": ["utf-8", "iso-8859-1", "ascii"],
  "Accept-Encoding": [
    "gzip, deflate, br",
    "gzip",
    "deflate",
    "br",
    "identity",
    "gzip, deflate",
  ],
  "Accept-Language": [
    "en-US,en;q=0.9",
    "en-US",
    "en-GB",
    "fr-FR",
    "de-DE",
    "es-ES",
    "ja-JP",
    "zh-CN",
    "*",
  ],
  Authorization: ["Bearer ", "Basic ", "Digest ", "Token "],
  "Cache-Control": [
    "no-cache",
    "no-store",
    "max-age=0",
    "max-age=3600",
    "max-age=86400",
    "no-cache, no-store, must-revalidate",
    "public, max-age=31536000",
    "private",
    "must-revalidate",
  ],
  Connection: ["keep-alive", "close"],
  "Content-Disposition": [
    "attachment",
    "inline",
    'attachment; filename="file.txt"',
    'form-data; name="field"',
  ],
  "Content-Encoding": ["gzip", "deflate", "br", "identity"],
  "Content-Type": [
    "application/json",
    "application/json; charset=utf-8",
    "application/xml",
    "application/x-www-form-urlencoded",
    "multipart/form-data",
    "text/plain",
    "text/plain; charset=utf-8",
    "text/html",
    "text/html; charset=utf-8",
    "text/css",
    "text/csv",
    "application/javascript",
    "application/octet-stream",
    "application/pdf",
    "application/graphql",
    "application/ld+json",
    "application/soap+xml",
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/webp",
    "image/svg+xml",
  ],
  DNT: ["0", "1"],
  Expect: ["100-continue"],
  Forwarded: [
    "for=192.0.2.1",
    'for=192.0.2.1; proto=https; by=203.0.113.1; host="example.com"',
  ],
  "Keep-Alive": ["timeout=5, max=100"],
  Origin: ["http://localhost:3000", "https://example.com"],
  Pragma: ["no-cache"],
  Range: ["bytes=0-1023"],
  "Sec-Fetch-Dest": ["document", "empty", "image", "script", "style", "font"],
  "Sec-Fetch-Mode": ["cors", "navigate", "no-cors", "same-origin", "websocket"],
  "Sec-Fetch-Site": ["same-origin", "same-site", "cross-site", "none"],
  TE: ["trailers", "compress", "deflate", "gzip"],
  "Transfer-Encoding": ["chunked", "compress", "deflate", "gzip"],
  Upgrade: ["websocket", "h2c"],
  "User-Agent": [
    "ReqResFlow/1.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0",
  ],
  "X-Content-Type-Options": ["nosniff"],
  "X-Frame-Options": ["DENY", "SAMEORIGIN"],
  "X-Requested-With": ["XMLHttpRequest"],
  "X-XSS-Protection": ["0", "1", "1; mode=block"],
};
