import React, { useCallback, useState } from "react";
import { Reorder } from "motion/react";
import AutoGeneratedHeaders from "./components/AutoGeneratedHeaders";
import AuthEditor from "./components/AuthEditor";
import BodyEditor from "./components/BodyEditor";
import CapturesEditor from "./components/CapturesEditor";
import EnvManager from "./components/EnvManager";
import EnvironmentBar from "./components/EnvironmentBar";
import KeyValueEditor from "./components/KeyValueEditor";
import ResponsePanelComponent from "./components/ResponsePanel";
import SavePickerModal from "./components/SavePickerModal";
import Sidebar, { SidebarSection } from "./components/Sidebar";
import FlowEditor from "./components/FlowEditor";
import FlowRunner from "./components/FlowRunner";
import TabContextMenu from "./components/TabContextMenu";
import { TabItem, FlowTabItem } from "./components/TabItems";
import UrlBar from "./components/UrlBar";
import { useCollections } from "./hooks/useCollections";
import { useContextMenu } from "./hooks/useContextMenu";
import { useEnvironments } from "./hooks/useEnvironments";
import { useFlowExecution } from "./hooks/useFlowExecution";
import { useFlowTabs } from "./hooks/useFlowTabs";
import { useHistory } from "./hooks/useHistory";
import { usePayloads } from "./hooks/usePayloads";
import { useSaveToCollection } from "./hooks/useSaveToCollection";
import { useSendRequest } from "./hooks/useSendRequest";
import { useSession } from "./hooks/useSession";
import { useSidebarResize } from "./hooks/useSidebarResize";
import { useTabs } from "./hooks/useTabs";
import {
  parseQueryParams,
  getBaseUrl,
  buildQueryString,
} from "./utils/url";

type RequestPanel = "params" | "headers" | "body" | "auth" | "captures";
type ResponsePanel = "body" | "headers";

const App: React.FC = () => {
  // Tabs
  const {
    tabs,
    setTabs,
    activeTabId,
    setActiveTabId,
    activeTab,
    updateTab,
    addTab,
    closeTab,
    duplicateTab,
    closeAllTabs,
  } = useTabs();
  const [requestPanel, setRequestPanel] = useState<RequestPanel>("params");
  const [responsePanel, setResponsePanel] = useState<ResponsePanel>("body");
  const [loading, setLoading] = useState(false);

  // Collections
  const { collections, setCollections, handleCollectionsChange } =
    useCollections();

  // Environments
  const {
    environments,
    setEnvironments,
    activeEnvId,
    setActiveEnvId,
    activeEnv,
    showEnvManager,
    setShowEnvManager,
    handleEnvironmentsChange,
  } = useEnvironments();

  // History
  const { history, setHistory, clearHistory } = useHistory();

  // Sidebar resize
  const { sidebarWidth, handleResizeMouseDown } = useSidebarResize();

  // Sidebar section
  const [sidebarSection, setSidebarSection] =
    useState<SidebarSection>("collections");

  // Flows & flow tabs
  const {
    flows,
    setFlows,
    flowTabs,
    setFlowTabs,
    activeFlowTabId,
    setActiveFlowTabId,
    handleFlowsChange,
    openFlowTab,
    closeFlowTab,
    duplicateFlowTab,
    closeAllFlowTabs,
    handleCreateFlow,
    handleSaveFlow,
    handleEditFlow,
    handleFlowChange,
    handleRenameFlow,
  } = useFlowTabs({ onSidebarSectionChange: setSidebarSection });

  // Flow execution
  const {
    flowRunState,
    setFlowRunState,
    flowRunHistory,
    flowAbortRef,
    runFlow,
  } = useFlowExecution({
    collections,
    activeEnv,
    activeEnvId,
    environments,
    setEnvironments,
    setHistory,
    openFlowTab,
  });

  // Session loading & auto-save
  useSession({
    setTabs,
    setActiveTabId,
    setCollections,
    setEnvironments,
    setActiveEnvId,
    setHistory,
    setFlows,
    tabs,
    activeTabId,
    activeEnvId,
  });

  // Tab context menu
  const {
    menu: tabContextMenu,
    setMenu: setTabContextMenu,
    menuRef: tabContextMenuRef,
  } = useContextMenu<string>();

  // Flow tab context menu
  const {
    menu: flowTabContextMenu,
    setMenu: setFlowTabContextMenu,
    menuRef: flowTabContextMenuRef,
  } = useContextMenu<string>();

  // Handle sidebar section switching
  const handleSectionChange = useCallback((section: SidebarSection) => {
    setSidebarSection(section);
  }, []);

  // Payload & capture helpers
  const {
    activePayload,
    body,
    updatePayloadBody,
    addPayload,
    removePayload,
    renamePayload,
    addCapture,
    updateCapture,
    removeCapture,
  } = usePayloads(activeTab, updateTab, setCollections);

  // Send request, load request, history, variants
  const {
    sendRequest,
    getCurrentRequest,
    loadRequest,
    loadHistoryEntry,
    runVariant,
  } = useSendRequest({
    tabs,
    setTabs,
    activeTab,
    setActiveTabId,
    updateTab,
    activeEnv,
    activeEnvId,
    environments,
    setEnvironments,
    history,
    setHistory,
    activePayload,
    body,
    setLoading,
  });

  // Save to collection
  const {
    showSavePicker,
    setShowSavePicker,
    saveRequestToCollection,
    saveToPickedCollection,
  } = useSaveToCollection({
    activeTab,
    collections,
    setCollections,
    setTabs,
    getCurrentRequest,
  });

  // Rename active request and sync with collection if linked
  const renameActiveRequest = useCallback(
    (newName: string) => {
      if (!activeTab) return;
      updateTab(activeTab.id, { name: newName });
      if (activeTab.savedToCollectionId && activeTab.savedRequestId) {
        setCollections((prev) => {
          const updated = prev.map((c) => {
            if (c.id !== activeTab.savedToCollectionId) return c;
            return {
              ...c,
              requests: c.requests.map((r) =>
                r.id === activeTab.savedRequestId ? { ...r, name: newName } : r,
              ),
            };
          });
          window.electronAPI.saveCollections(updated);
          return updated;
        });
      }
    },
    [
      activeTab?.id,
      activeTab?.savedToCollectionId,
      activeTab?.savedRequestId,
      updateTab,
    ],
  );

  // Sync payload rename from sidebar to open tab
  const handleRenamePayload = useCallback(
    (
      collectionId: string,
      requestId: string,
      payloadId: string,
      name: string,
    ) => {
      setTabs((prev) =>
        prev.map((t) => {
          if (
            t.savedToCollectionId !== collectionId ||
            t.savedRequestId !== requestId
          )
            return t;
          return {
            ...t,
            payloads: t.payloads.map((p) =>
              p.id === payloadId ? { ...p, name } : p,
            ),
          };
        }),
      );
    },
    [],
  );

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") sendRequest();
  };

  const response = activeTab?.response ?? null;
  const error = activeTab?.error ?? null;

  return (
    <div className="app">
      {/* Sidebar */}
      <Sidebar
        collections={collections}
        onCollectionsChange={handleCollectionsChange}
        onLoadRequest={loadRequest}
        onSaveRequest={getCurrentRequest}
        history={history}
        onLoadHistory={loadHistoryEntry}
        onClearHistory={clearHistory}
        activeCollectionId={activeTab?.savedToCollectionId ?? null}
        activeRequestId={activeTab?.savedRequestId ?? null}
        flows={flows}
        onFlowsChange={handleFlowsChange}
        onEditFlow={handleEditFlow}
        onRunFlow={runFlow}
        onCreateFlow={handleCreateFlow}
        onRenameFlow={handleRenameFlow}
        onRunVariant={runVariant}
        onRenamePayload={handleRenamePayload}
        onRequestPanelChange={(p: string) => setRequestPanel(p as RequestPanel)}
        activeSection={sidebarSection}
        onSectionChange={handleSectionChange}
        activeFlowId={
          flowTabs.find((ft) => ft.id === activeFlowTabId)?.flowId ?? null
        }
        style={{ width: sidebarWidth }}
      />

      {/* Resize Handle */}
      <div
        className="sidebar-resize-handle"
        onMouseDown={handleResizeMouseDown}
      />

      {/* Main Panel */}
      <div className="main-panel">
        {/* Tabs Bar */}
        <div className="request-tabs-bar">
          {sidebarSection !== "flows" && (
            <>
              <div className="request-tabs-scroll">
                <Reorder.Group
                  as="div"
                  axis="x"
                  values={tabs}
                  onReorder={setTabs}
                  className="request-tabs-list"
                >
                  {tabs.map((tab) => (
                    <TabItem
                      key={tab.id}
                      tab={tab}
                      isActive={tab.id === activeTabId}
                      onActivate={() => setActiveTabId(tab.id)}
                      onClose={() => closeTab(tab.id)}
                      onContextMenu={(e) => {
                        e.preventDefault();
                        setTabContextMenu({
                          x: e.clientX,
                          y: e.clientY,
                          tabId: tab.id,
                        });
                      }}
                    />
                  ))}
                </Reorder.Group>
              </div>
              <button
                className="request-tab-add"
                onClick={addTab}
                title="New Tab"
              >
                +
              </button>
            </>
          )}
          {sidebarSection === "flows" && (
            <>
              <div className="request-tabs-scroll">
                <Reorder.Group
                  as="div"
                  axis="x"
                  values={flowTabs}
                  onReorder={setFlowTabs}
                  className="request-tabs-list"
                >
                  {flowTabs.map((ft) => (
                    <FlowTabItem
                      key={ft.id}
                      tab={ft}
                      isActive={ft.id === activeFlowTabId}
                      onActivate={() => setActiveFlowTabId(ft.id)}
                      onClose={() => closeFlowTab(ft.id)}
                      onContextMenu={(e) => {
                        e.preventDefault();
                        setFlowTabContextMenu({
                          x: e.clientX,
                          y: e.clientY,
                          tabId: ft.id,
                        });
                      }}
                    />
                  ))}
                </Reorder.Group>
              </div>
              <button
                className="request-tab-add"
                onClick={handleCreateFlow}
                title="New Flow"
              >
                +
              </button>
            </>
          )}
        </div>

        {/* Flow Tab Context Menu */}
        {flowTabContextMenu && (
          <TabContextMenu
            x={flowTabContextMenu.x}
            y={flowTabContextMenu.y}
            menuRef={flowTabContextMenuRef}
            duplicateLabel="Duplicate Flow"
            onDuplicate={() => duplicateFlowTab(flowTabContextMenu.tabId)}
            onClose={() => closeFlowTab(flowTabContextMenu.tabId)}
            onCloseAll={closeAllFlowTabs}
            onDismiss={() => setFlowTabContextMenu(null)}
          />
        )}

        {sidebarSection !== "flows" && (
          <>
            {/* Tab Context Menu */}
            {tabContextMenu && (
              <TabContextMenu
                x={tabContextMenu.x}
                y={tabContextMenu.y}
                menuRef={tabContextMenuRef}
                onDuplicate={() => duplicateTab(tabContextMenu.tabId)}
                onClose={() => closeTab(tabContextMenu.tabId)}
                onCloseAll={closeAllTabs}
                onDismiss={() => setTabContextMenu(null)}
              />
            )}

            {!activeTab && (
              <div className="empty-state">
                <div className="empty-state-icon">↗</div>
                <div className="empty-state-title">No open requests</div>
                <div className="empty-state-hint">
                  Open a request from a collection, history, or create a new tab
                  with the + button above.
                </div>
              </div>
            )}

            {activeTab && (
              <>
                {/* Environment Bar */}
                <EnvironmentBar
                  requestName={activeTab.name}
                  environments={environments}
                  activeEnvId={activeEnvId}
                  onRename={renameActiveRequest}
                  onEnvChange={setActiveEnvId}
                  onManageEnvs={() => setShowEnvManager(true)}
                />

                {/* URL Bar */}
                <UrlBar
                  method={activeTab.method}
                  url={activeTab.url}
                  loading={loading}
                  isDirty={activeTab.isDirty}
                  savedRequestId={activeTab.savedRequestId}
                  envVariables={activeEnv?.variables ?? []}
                  envName={activeEnv?.name}
                  onMethodChange={(method) => updateTab(activeTab.id, { method })}
                  onUrlChange={(v) => {
                    const parsed = parseQueryParams(v);
                    const params =
                      parsed.length > 0
                        ? [...parsed, { enabled: true, key: "", value: "" }]
                        : [{ enabled: true, key: "", value: "" }];
                    updateTab(activeTab.id, { url: v, params });
                  }}
                  onSend={sendRequest}
                  onSave={saveRequestToCollection}
                  onKeyDown={handleKeyDown}
                />

                <div className="request-response">
                  {/* Request Section */}
                  <div className="request-section">
                    <div className="tabs">
                      {(
                        [
                          "params",
                          "headers",
                          "body",
                          "auth",
                          "captures",
                        ] as RequestPanel[]
                      ).map((tab) => (
                        <button
                          key={tab}
                          className={`tab ${requestPanel === tab ? "active" : ""}`}
                          onClick={() => setRequestPanel(tab)}
                        >
                          {tab}
                          {tab === "auth" && activeTab.auth.type !== "none" && (
                            <span className="tab-badge">●</span>
                          )}
                          {tab === "captures" &&
                            activeTab.captures.length > 0 && (
                              <span className="tab-badge">
                                {
                                  activeTab.captures.filter((c) => c.enabled)
                                    .length
                                }
                              </span>
                            )}
                        </button>
                      ))}
                    </div>

                    {requestPanel === "params" && (
                      <KeyValueEditor
                        pairs={activeTab.params}
                        onChange={(p) => {
                          const base = getBaseUrl(activeTab.url);
                          const qs = buildQueryString(p);
                          const url = qs ? `${base}?${qs}` : base;
                          updateTab(activeTab.id, { params: p, url });
                        }}
                        variables={activeEnv?.variables ?? []}
                        envName={activeEnv?.name}
                      />
                    )}
                    {requestPanel === "headers" && (
                      <>
                        <KeyValueEditor
                          pairs={activeTab.headers}
                          onChange={(h) =>
                            updateTab(activeTab.id, { headers: h })
                          }
                          variables={activeEnv?.variables ?? []}
                          envName={activeEnv?.name}
                          headerMode
                        />
                        <AutoGeneratedHeaders
                          bodyType={activeTab.bodyType}
                          rawLanguage={activeTab.rawLanguage}
                          headers={activeTab.headers}
                        />
                      </>
                    )}
                    {requestPanel === "body" && (
                      <BodyEditor
                        tab={activeTab}
                        activePayload={activePayload}
                        body={body}
                        envVariables={activeEnv?.variables ?? []}
                        envName={activeEnv?.name}
                        onUpdateTab={(updates) => updateTab(activeTab.id, updates)}
                        onAddPayload={addPayload}
                        onRemovePayload={removePayload}
                        onRenamePayload={renamePayload}
                        onUpdatePayloadBody={updatePayloadBody}
                      />
                    )}
                    {requestPanel === "auth" && (
                      <AuthEditor
                        auth={activeTab.auth}
                        envVariables={activeEnv?.variables ?? []}
                        envName={activeEnv?.name}
                        onAuthChange={(auth) => updateTab(activeTab.id, { auth })}
                      />
                    )}
                    {requestPanel === "captures" && (
                      <CapturesEditor
                        captures={activeTab.captures}
                        activeEnvId={activeEnvId}
                        onAdd={addCapture}
                        onUpdate={updateCapture}
                        onRemove={removeCapture}
                      />
                    )}
                  </div>

                  {/* Response Section */}
                  <ResponsePanelComponent
                    response={response}
                    error={error}
                    responsePanel={responsePanel}
                    onPanelChange={setResponsePanel}
                  />
                </div>
              </>
            )}
          </>
        )}

        {sidebarSection === "flows" && (
          <div className="flow-tab-content">
            {(() => {
              const activeFlowTab = flowTabs.find(
                (ft) => ft.id === activeFlowTabId,
              );
              if (!activeFlowTab) {
                return (
                  <div className="flow-empty-state">
                    Open or create a flow to get started
                  </div>
                );
              }
              const flow = flows.find((f) => f.id === activeFlowTab.flowId);
              if (!flow) {
                return (
                  <div className="flow-empty-state">
                    Flow not found — it may have been deleted
                  </div>
                );
              }
              if (activeFlowTab.mode === "runner" && flowRunState) {
                return (
                  <FlowRunner
                    runState={flowRunState}
                    onClose={() => {
                      setFlowTabs((prev) =>
                        prev.map((ft) =>
                          ft.id === activeFlowTab.id
                            ? { ...ft, mode: "editor" }
                            : ft,
                        ),
                      );
                      setFlowRunState(null);
                    }}
                    onAbort={() => {
                      flowAbortRef.current = true;
                    }}
                  />
                );
              }
              return (
                <FlowEditor
                  key={activeFlowTab.id}
                  flow={flow}
                  collections={collections}
                  onSave={handleSaveFlow}
                  onCancel={() => closeFlowTab(activeFlowTab.id)}
                  onRun={runFlow}
                  onChange={handleFlowChange}
                  lastRunState={flowRunHistory[flow.id] ?? null}
                />
              );
            })()}
          </div>
        )}
      </div>

      {/* Environment Manager Modal */}
      {showEnvManager && (
        <EnvManager
          environments={environments}
          onEnvironmentsChange={handleEnvironmentsChange}
          onClose={() => setShowEnvManager(false)}
        />
      )}

      {/* Save to Collection Picker Modal */}
      {showSavePicker && (
        <SavePickerModal
          collections={collections}
          onSave={saveToPickedCollection}
          onClose={() => setShowSavePicker(false)}
        />
      )}
    </div>
  );
};

export default App;
