/**
 * Central selector constants for all E2E tests.
 * Uses CSS class selectors matching the actual app DOM.
 */
export const S = {
  // ── Root ──
  app: ".app",

  // ── Tab Bar ──
  tabBar: ".request-tabs-bar",
  tabList: ".request-tabs-list",
  tabItem: ".request-tab-item",
  tabItemActive: ".request-tab-item.active",
  tabMethod: ".request-tab-method",
  tabName: ".request-tab-name",
  tabDirty: ".request-tab-dirty",
  tabClose: ".request-tab-close",
  tabAdd: ".request-tab-add",
  tabContextMenu: ".tab-context-menu",

  // ── Env Bar ──
  envBar: ".env-bar",
  requestNameInput: ".request-name-input",
  envSelect: ".env-select",
  envManageBtn: ".env-manage-btn",

  // ── URL Bar ──
  urlBar: ".url-bar",
  methodSelect: ".method-select",
  urlInput: ".url-input",
  sendBtn: ".send-btn",
  saveBtn: ".save-btn",

  // ── Request Panel ──
  requestSection: ".request-section",
  requestTab: ".request-section .tab",
  requestTabActive: ".request-section .tab.active",
  tabBadge: ".tab-badge",

  // ── Params ──
  kvEditor: ".kv-editor",
  kvRow: ".kv-row",
  kvAddBtn: ".kv-add-btn",
  kvRemoveBtn: ".kv-remove-btn",

  // ── Body ──
  bodyEditor: ".body-editor",
  bodyTypeBar: ".body-type-bar",
  bodyTypeOption: ".body-type-option",
  rawLanguageSelect: ".raw-language-select",
  bodyNoneInfo: ".body-none-info",
  formDataEditor: ".form-data-editor",
  formDataRow: ".form-data-row",
  formDataTypeSelect: ".form-data-type-select",
  binaryEditor: ".binary-editor",
  binaryPathInput: ".binary-path-input",
  graphqlEditor: ".graphql-editor",
  graphqlSection: ".graphql-section",
  graphqlLabel: ".graphql-label",

  // ── Payloads ──
  payloadBar: ".payload-bar",
  payloadTabs: ".payload-tabs",
  payloadTab: ".payload-tab",
  payloadTabActive: ".payload-tab.active",
  payloadTabName: ".payload-tab-name",
  payloadTabClose: ".payload-tab-close",
  payloadAddBtn: ".payload-add-btn",
  payloadRenameInput: ".payload-rename-input",

  // ── Auth ──
  authEditor: ".auth-editor",
  authTypeSelect: ".auth-type-select",
  authFields: ".auth-fields",
  authField: ".auth-field",
  authLabel: ".auth-label",
  authInput: ".auth-input",
  authInfo: ".auth-info",

  // ── Captures ──
  capturesEditor: ".captures-editor",
  capturesInfo: ".captures-info",
  capturesWarning: ".captures-warning",
  capturesEmpty: ".captures-empty",
  captureRow: ".capture-row",
  captureVarInput: ".capture-var-input",
  captureSourceSelect: ".capture-source-select",
  capturePathInput: ".capture-path-input",
  captureRemoveBtn: ".capture-remove-btn",
  captureAddBtn: ".capture-add-btn",

  // ── Response Panel ──
  responseSection: ".response-section",
  responseTab: ".response-section .tab",
  responseMeta: ".response-meta",
  responseStatus: ".response-status",
  responseTime: ".response-time",
  responseSize: ".response-size",
  responseBody: ".response-body",
  responseError: ".response-error",
  responseEmpty: ".response-empty",
  responseHeadersList: ".response-headers-list",
  responseHeaderRow: ".response-header-row",
  responseHeaderKey: ".response-header-key",
  responseHeaderValue: ".response-header-value",

  // ── Autogenerated Headers ──
  autogeneratedHeaders: ".autogenerated-headers",
  autogeneratedHeaderRow: ".autogenerated-header-row",

  // ── Code Editor ──
  codeEditorWrapper: ".code-editor-wrapper",
  formatBtn: ".format-btn",

  // ── Sidebar ──
  sidebar: ".sidebar",
  sidebarResizeHandle: ".sidebar-resize-handle",
  sidebarSectionTabs: ".sidebar-section-tabs",
  sidebarSectionTab: ".sidebar-section-tab",
  sidebarSectionTabActive: ".sidebar-section-tab.active",
  sidebarHeader: ".sidebar-header",
  sidebarHeaderTitle: ".sidebar-header-title",
  sidebarAddBtn: ".sidebar-add-btn",
  sidebarContent: ".sidebar-content",
  sidebarEmpty: ".sidebar-empty",

  // ── Collections ──
  collection: ".collection",
  collectionHeader: ".collection-header",
  collectionArrow: ".collection-arrow",
  collectionName: ".collection-name",
  collectionActions: ".collection-actions",
  collectionRequests: ".collection-requests",
  requestItem: ".request-item",
  requestItemActive: ".request-item.active",
  requestMethodBadge: ".request-method-badge",
  requestName: ".request-name",
  renameInput: ".rename-input",
  sidebarIconBtn: ".sidebar-icon-btn",
  sidebarIconBtnDanger: ".sidebar-icon-btn.danger",

  // ── Request Variants ──
  requestVariants: ".request-variants",
  requestVariantItem: ".request-variant-item",
  requestVariantName: ".request-variant-name",
  requestVariantPlay: ".request-variant-play",

  // ── History ──
  historyItem: ".history-item",
  historyItemTop: ".history-item-top",
  historyStatus: ".history-status",
  historyTime: ".history-time",
  historyItemUrl: ".history-item-url",
  historyBadge: ".history-badge",

  // ── Flows (sidebar) ──
  flowItem: ".flow-item",
  flowItemHeader: ".flow-item-header",
  flowItemName: ".flow-item-name",
  flowItemSteps: ".flow-item-steps",

  // ── Env Manager Modal ──
  modalOverlay: ".modal-overlay",
  modal: ".modal",
  modalHeader: ".modal-header",
  modalCloseBtn: ".modal-close-btn",
  envManagerBody: ".env-manager-body",
  envList: ".env-list",
  envListItem: ".env-list-item",
  envListItemActive: ".env-list-item.active",
  envNameInput: ".env-name-input",
  envVarRow: ".env-var-row",

  // ── Save Picker Modal ──
  savePickerModal: ".save-picker-modal",
  savePickerHeader: ".save-picker-header",
  savePickerClose: ".save-picker-close",
  savePickerBody: ".save-picker-body",
  savePickerEmpty: ".save-picker-empty",
  savePickerList: ".save-picker-list",
  savePickerItem: ".save-picker-item",

  // ── Flow Editor (rendered as tab content, not an overlay) ──
  flowTabContent: ".flow-tab-content",
  flowEmptyState: ".flow-empty-state",
  flowEditor: ".flow-editor",
  flowEditorName: ".flow-editor-name",
  flowEditorActions: ".flow-editor-actions",
  flowEditorBtn: ".flow-editor-btn",
  flowEditorBtnPrimary: ".flow-editor-btn.primary",
  flowEditorBtnSecondary: ".flow-editor-btn.secondary",
  flowSteps: ".flow-steps",
  flowStepsEmpty: ".flow-steps-empty",
  flowStep: ".flow-step",
  flowStepHeader: ".flow-step-header",
  flowStepIndex: ".flow-step-index",
  flowStepMethod: ".flow-step-method",
  flowStepName: ".flow-step-name",
  flowStepMissing: ".flow-step-missing",
  flowStepMove: ".flow-step-move",
  flowStepRemove: ".flow-step-remove",
  flowStepDetail: ".flow-step-detail",
  flowStepCheckbox: ".flow-step-checkbox",
  flowStepControls: ".flow-step-controls",
  flowStepConnector: ".flow-step-connector",
  flowAddStepBtn: ".flow-add-step-btn",
  flowRequestPicker: ".flow-request-picker",
  flowRequestPickerItem: ".flow-request-picker-item",

  // ── Flow Step Captures ──
  flowStepCaptures: ".flow-step-captures",
  flowStepCapturesHeader: ".flow-step-captures-header",
  flowStepCapturesAdd: ".flow-step-captures-add",
  flowStepCapturesEmpty: ".flow-step-captures-empty",
  flowStepCaptureRow: ".flow-step-capture-row",
  flowStepCaptureInput: ".flow-step-capture-input",
  flowStepCaptureSelect: ".flow-step-capture-select",
  flowStepCaptureRemove: ".flow-step-capture-remove",

  // ── Flow Editor Last Run ──
  flowEditorLastRun: ".flow-editor-last-run",
  flowEditorLastRunHeader: ".flow-editor-last-run-header",
  flowEditorLastRunTitle: ".flow-editor-last-run-title",
  flowEditorLastRunSummary: ".flow-editor-last-run-summary",
  flowEditorLastRunBody: ".flow-editor-last-run-body",
  flowEditorLastRunSteps: ".flow-editor-last-run-steps",
  flowEditorLastRunStep: '[class*="flow-editor-last-run-step"]',

  // ── Flow Runner (rendered as tab content) ──
  flowRunner: ".flow-runner",
  flowRunnerHeader: ".flow-runner-header",
  flowRunnerTitle: ".flow-runner-title",
  flowRunnerSummary: ".flow-runner-summary",
  flowRunnerRunning: ".flow-runner-running",
  flowRunnerSteps: ".flow-runner-steps",
  flowRunnerStep: ".flow-runner-step",
  flowRunnerStepIcon: ".flow-runner-step-icon",
  flowRunnerStepMethod: ".flow-runner-step-method",
  flowRunnerStepName: ".flow-runner-step-name",
  flowRunnerStepStatus: '[class*="flow-runner-step-status"]',
  flowRunnerStepTime: ".flow-runner-step-time",
  flowRunnerDetailPanel: ".flow-runner-detail-panel",
  flowRunnerDetailTab: ".flow-runner-detail-tab",
  flowRunnerDetailEmpty: ".flow-runner-detail-empty",
  flowRunnerCapturesTable: ".flow-runner-captures-table",

  // ── Sidebar Play Buttons ──
  requestPlayBtn: ".request-play-btn",
  requestVariantPlayBtn: ".request-variant-play",

  // ── AutoSuggest ──
  autosuggestWrapper: ".autosuggest-wrapper",
  autosuggestDropdown: ".autosuggest-dropdown",
  autosuggestItem: ".autosuggest-item",
  autosuggestItemSelected: ".autosuggest-item.selected",
  envVarHighlight: ".env-var-highlight",
  envVarTooltip: ".env-var-tooltip",
  envVarTooltipWarning: ".env-var-tooltip-warning",
} as const;
